""" migrations_tr

Revision ID: 71e61963fea9
Revises: 7f3b1533f52c
Create Date: 2023-05-28 20:49:02.925161

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "71e61963fea9"
down_revision = "7f3b1533f52c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("direction_2", sa.String(), nullable=True),
        sa.Column("direction_3", sa.String(), nullable=True),
        sa.Column("Offline", sa.Boolean(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("start", sa.String(), nullable=True),
        sa.Column("end", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attends_id"), "attends", ["id"], unique=False)
    op.drop_index("groups_id_idx", table_name="groups")
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.create_index("groups_id_idx", "groups", ["id"], unique=False)
    op.drop_index(op.f("ix_attends_id"), table_name="attends")
    op.drop_table("attends")
    # ### end Alembic commands ###
