""" migrations_tr

Revision ID: 7f3b1533f52c
Revises: 0f1df45c373e
Create Date: 2023-05-28 01:42:51.700780

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7f3b1533f52c"
down_revision = "0f1df45c373e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_name", table_name="users312")
    op.drop_table("users312")
    op.drop_table("users1")
    op.alter_column("users", "id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.alter_column("users", "id", existing_type=sa.INTEGER(), nullable=True)
    op.create_table(
        "users1",
        sa.Column("уникальный номер", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "дата создание личного дела",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("пол", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "дата рождения", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "адрес проживания",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "users312",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("sex", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("birthday_date", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_users_name", "users312", ["name"], unique=False)
    # ### end Alembic commands ###
