""" migrations_tr

Revision ID: 860804179da1
Revises: 71e61963fea9
Create Date: 2023-05-28 21:24:50.456572

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "860804179da1"
down_revision = "71e61963fea9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
