""" migrations_tr

Revision ID: 9e81207c2607
Revises: a8c3c554939d
Create Date: 2023-05-27 20:19:41.159415

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9e81207c2607"
down_revision = "a8c3c554939d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_uniquegroups_id", table_name="uniquegroups1")
    op.drop_table("uniquegroups1")
    op.drop_table("users1")
    op.alter_column(
        "groups", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.alter_column(
        "uniquegroups",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.create_index(op.f("ix_uniquegroups_id"), "uniquegroups", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uniquegroups_id"), table_name="uniquegroups")
    op.alter_column(
        "uniquegroups",
        "id",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.alter_column(
        "groups", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.create_table(
        "users1",
        sa.Column("уникальный номер", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "дата создание личного дела",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("пол", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "дата рождения", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "адрес проживания",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "uniquegroups1",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("direction_1", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("direction_2", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("direction_3", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("okrug", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("district", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("schedule_active", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("schedule_closed", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("schedule_planned", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("closest_smetro", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "coordinates_of_address", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_uniquegroups_id", "uniquegroups1", ["id"], unique=False)
    # ### end Alembic commands ###
