""" migrations_tr

Revision ID: a8c3c554939d
Revises: 5235f48038fa
Create Date: 2023-05-26 14:46:28.589244

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a8c3c554939d"
down_revision = "5235f48038fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
