""" migrations_tr

Revision ID: f9a30bb31a7d
Revises: 
Create Date: 2023-05-25 13:10:00.080931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a30bb31a7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_1', sa.String(), nullable=True),
    sa.Column('direction_2', sa.String(), nullable=True),
    sa.Column('direction_3', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('okrug', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('schedule_active', sa.String(), nullable=True),
    sa.Column('schedule_closed', sa.String(), nullable=True),
    sa.Column('schedule_planned', sa.String(), nullable=True),
    sa.Column('closest_smetro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('birthday_date', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('unique_addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unique_addresses',
    sa.Column('адрес площадки', sa.VARCHAR(length=2048), autoincrement=False, nullable=True)
    )
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
